description: The 18th Workshop on Models and Evolution (ME) 2024 is a satellite event at ACM/IEEE 27th International Conference on Model Driven Engineering Languages and Systems.
author: Djamel Eddine Khelladi, Juri Di Rocco, and Dalila Tamzalit.
keywords: ME, Model-Driven Engineering, Evolution, MDE, coevolution

url: https://models-and-evolution.github.io
cfp-url: https://conference-hall.io/public/event/98FptSgEGcOSQZymZkUr
name: Models and Evolution

day1: Sunday 22 
day2: Friday 27
month: September 2024
data-year: 2024
data-month: 09
data-day: 22
data-hour: 09

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - .gitignore
  - CNAME

navigation:
 - title: Call for Papers
   url: /call-for-paper/
# - title: Program
#   url: /speakers/
 - title: Important Dates
   url: /sponsors/
 - title: Organizers
   url: /orga/
 - title: Past Editions
   url: /past-editions/
 - title: Contact
   url: /contacts/


collections:
  speakers:
    output: true
    permalink: /:collection/:name
  talks:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talks
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
  - scope:
      path: "speakers/tbd"
    values:
      sitemap: false
  - scope:
      path: "speakers/volcamp"
    values:
      sitemap: false

syndication:
  twitter: http://www.twitter.com/models-evolution
  github: https://github.com/models-and-evolution
  linkedin: https://www.linkedin.com/company/volcampio
  youtube: https://www.youtube.com/channel/UC5iGUFHEJbSTU5wpbT6KIcw/featured

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-minifier
  - kramdown-parser-gfm

